substitutions:
  name: petlibro-feeder-0

esphome:
  name: ${name}

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_petlibrofeeder_0
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
  ap:
    ssid: "${name}-AP"
    password: !secret wifi_password
    ap_timeout: 3min

captive_portal:

logger:

api:
  id: api_id

ota:

globals:
  - id: button_counter
    type: int
    initial_value: '0'
  - id: target_number
    type: int
    initial_value: '1'

button:
  - platform: template
    name: "Feed"
    icon: "mdi:cat"
    on_press:
      - lambda: |-
            HomeassistantServiceResponse resp;
            resp.service = "switch.turn_on";
            HomeassistantServiceMap entity_id_kv;
            entity_id_kv.key = "entity_id";
            entity_id_kv.value = "switch.motor";
            resp.data.push_back(entity_id_kv);
            id(api_id).send_homeassistant_service_call(resp);

            id(button_counter) = 0;

number:
  - platform: template
    name: "Portions"
    step: 1
    min_value: 1
    max_value: 10
    mode: slider
    set_action:
      then:
        - lambda:  id(target_number) = x;

switch:
  - platform: gpio
    id: motor
    name: "Motor"
    pin: D2
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    id: encoder_switch
    name: "Encoder"
    pin:
      number: D1
      mode: INPUT_PULLUP
    filters:
      - delayed_on:  10ms
      - delayed_off: 10ms
    on_press:
      then:
        - lambda: |-
            id(button_counter) += 1;
            if (id(button_counter) >= id(target_number)) {
              HomeassistantServiceResponse resp;
              resp.service = "switch.turn_off";
              HomeassistantServiceMap entity_id_kv;
              entity_id_kv.key = "entity_id";
              entity_id_kv.value = "switch.motor";
              resp.data.push_back(entity_id_kv);
              id(api_id).send_homeassistant_service_call(resp);

              id(button_counter) = 0;
            }

sensor:
  - platform: ultrasonic
    name: "Food Level"
    trigger_pin: D6
    echo_pin: D5
